pydev debugger: process 8324 is connecting

('109.104.178.163', 43622)
the JSON object must be str, bytes or bytearray, not list
[2019-03-26 20:06:47,462] [INFO]) 20:06:47:462365	Client: 109.104.178.163 sent data: auth_me:tRnPpqSTfpT5
INFO:utils_26-03-2019.log:20:06:47:462365	Client: 109.104.178.163 sent data: auth_me:tRnPpqSTfpT5
[2019-03-26 20:06:47,469] [INFO]) 20:06:47:469365	Auth - Fail: User: tRnPpqSTfpT5V6vJyjPF6ZjMK6AX7EcN is not whitelisted
INFO:utils_26-03-2019.log:20:06:47:469365	Auth - Fail: User: tRnPpqSTfpT5V6vJyjPF6ZjMK6AX7EcN is not whitelisted
